[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm turbo run build --filter=@zsn/queue-processor"

[deploy]
startCommand = "node dist/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[deploy.scaling]
minInstances = 1
maxInstances = 1
